name: Integration

on:
  - push

jobs:
  test:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Docker builder
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ secrets.DOCKER_IMAGE }}:latest
          push: false

      - name: Test
        run: |
          docker run --rm -v "${PWD}/test:/data" ghcr.io/LeoColomb/.docs "/data/Fixture.md" \
            --output "/data/Output.pdf" \
            --variable title="Fixture" \
            --variable id="Id" \
            --template="/opt/template.tex" \
            --pdf-engine=xelatex
